# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title

exclude: [
  "node_modules",
  "build",
  "styles",
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "Gruntfile.js",
  "report.html",
  ".jscs.json",
  ".jshintrc",
  ".gitattributes",
  ".gitignore",
  "package.json"
]
highlighter: pygments

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Incronaut
description: A website where we use various forms of media to express and share our interests.
tagline: Podcasting, blogs, and other projects.
base_url: http://incronaut.com

author :
  name : Christopher Chu
  email : incronaut@gmail.com

# navigation data used to generate header nav
main_navigation:
- text: About
  url: /about/
- text: FAQ
  url: /faq/
- text: Archive
  url: /archive/

feed_navigation:
- text: iTunes
  url: https://itunes.apple.com/us/podcast/npc-talk/id1027689993
  icon: icon-podcast
- text: RSS
  url: /feed.xml
  icon: icon-rss

comments :
  disqus:
    shortname: incronaut